### ISSUE TITLE
Pascal cards

### ISSUE THREAD

**Issue by Celebrandil** [Celebrandil/CudaSift#10]
Has anyone tried the code other Pascal cards? I really would like to see the performance on NVidia Titan X. Unfortunately, I haven't get been able to order one.

**Comment by riyueshi** [comment]
I got this on Titan X:
Image size = (1280,960)
Initializing data...
Device Number: 0
  Device name: GeForce GTX TITAN X
  Memory Clock Rate (MHz): 3505
  Memory Bus Width (bits): 384
  Peak Memory Bandwidth (GB/s): 336.5

Download time =               1.05 ms
Download time =               0.97 ms
GPU time : 0.10 ms + 0.29 ms + 0.14 ms = 0.53 ms
           0.06 ms / DoG,  0.0051 ms / Sift,  #Sift = 28
ExtractSift time total =      0.83 ms

GPU time : 0.10 ms + 0.23 ms + 0.14 ms = 0.46 ms
           0.05 ms / DoG,  0.0018 ms / Sift,  #Sift = 80
ExtractSift time total =      1.80 ms

GPU time : 0.10 ms + 0.29 ms + 0.15 ms = 0.54 ms
           0.06 ms / DoG,  0.0008 ms / Sift,  #Sift = 186
ExtractSift time total =      2.79 ms

GPU time : 0.10 ms + 0.61 ms + 0.18 ms = 0.89 ms
           0.12 ms / DoG,  0.0006 ms / Sift,  #Sift = 321
ExtractSift time total =      4.26 ms

GPU time : 0.12 ms + 1.93 ms + 0.22 ms = 2.27 ms
           0.39 ms / DoG,  0.0008 ms / Sift,  #Sift = 270
ExtractSift time total =      7.25 ms

GPU time : 0.09 ms + 0.31 ms + 0.14 ms = 0.55 ms
           0.06 ms / DoG,  0.0034 ms / Sift,  #Sift = 41
ExtractSift time total =      1.02 ms

GPU time : 0.11 ms + 0.35 ms + 0.15 ms = 0.61 ms
           0.07 ms / DoG,  0.0013 ms / Sift,  #Sift = 116
ExtractSift time total =      2.69 ms

GPU time : 0.10 ms + 0.33 ms + 0.17 ms = 0.60 ms
           0.07 ms / DoG,  0.0006 ms / Sift,  #Sift = 293
ExtractSift time total =      4.20 ms

GPU time : 0.11 ms + 0.61 ms + 0.21 ms = 0.93 ms
           0.12 ms / DoG,  0.0004 ms / Sift,  #Sift = 513
ExtractSift time total =      5.78 ms

GPU time : 0.09 ms + 2.00 ms + 0.19 ms = 2.29 ms
           0.40 ms / DoG,  0.0006 ms / Sift,  #Sift = 308
ExtractSift time total =      8.92 ms

MatchSiftData time =          1.09 ms
FindHomography time =         2.84 ms
Number of original features: 885 1271
Number of matching features: 431 470 53.1073%

**Comment by Celebrandil** [comment]
That is slower than I would expect. However, the card seems to be a GTX Titan X (Maxwell), which is not the same card as the NVidia Titan X (Pascal). Annoying reuse of a fancy name.

**Comment by riyueshi** [comment]
my fault. I am not familiar with the GPU hardware
