### ISSUE TITLE
Build error “cmd.exe” exit with code 1

### ISSUE THREAD

**Issue by riyueshi** [Celebrandil/CudaSift#11]
Hi, Celebrandil
  I want to build this project on my PC under the following conditions: 
Branch: Maxwell
IDE: vs2015
cuda version: v 8.0
GPU: NVidia Titan X 
but I got the following error in vs2015: 
>  Building NVCC (Device) object CMakeFiles/cudasift.dir/Release/cudasift_generated_cudaImage.cu.obj
1>  nvcc fatal   : redefinition of argument 'gpu-architecture'
1>  CMake Error at cudasift_generated_cudaImage.cu.obj.Release.cmake:222 (message):
1>    Error generating
F:/MillerWorkPath/VSProject/CudaSift/Bin/CMakeFiles/cudasift.dir//Release/cudasift_generated_cudaImage.cu.obj
and the error message MSB6006: “cmd.exe” exit with code 1.
I am not familiar with the GPU programming, can you give me some tips to fix this problem, Thanks.
Miller

**Comment by riyueshi** [comment]
The problem was fixed by delete " OPTIONS -arch=sm_61" on cmakelist.txt line 57

**Comment by Celebrandil** [comment]
Good to see you managed to solve it.

**Comment by lishanlei** [comment]
My cmakelist.txt infor is " OPTIONS -arch=sm_35 ". After deleting that ,I still couldn't solve this problem,Could you help me?

**Comment by yangninghua** [comment]
> My cmakelist.txt infor is " OPTIONS -arch=sm_35 ". After deleting that ,I still couldn't solve this problem,Could you help me?

Have you solved it?

**Comment by lishanlei** [comment]
Sorry，I have not. Otherwise I have tried used the SiftGPU which is authorized by Changchang Wu, but there are many wrong correspondence feature points with wrong descriptors. What do you think of that?

**Comment by yangninghua** [comment]
> 对不起，我没有。否则我试过使用了常昌武授权的SiftGPU，但是有很多错误的对应特征点和错误的描述符。你对那个怎么想的？

I am both trying, my English is not very good, are you Chinese? If so, we can add friends and privately explore the acceleration of sift.

**Comment by lishanlei** [comment]
大水冲了龙王庙，我也是中国人，在北京。若需交流，加我qq吧，458703142

**Comment by mintisan** [comment]
remove duplicated flag -arch=sm_62 works for me
