### ISSUE TITLE
Potential Memory Leak in cudaSiftH.cu

### ISSUE THREAD

**Issue by mefathy** [Celebrandil/CudaSift#12]
Hello,

Thanks for keeping this project active. There is, however, a potential memory leak in `cudaSiftH.cu`. In particular, the host memory is allocated twice using `malloc()` then `cudaMallocHost()` at lines 226 and 227, respectively. Either one of them is enough and the other one may need to be removed.

**Comment by Celebrandil** [comment]
Thank you very much. I should have seen that one.
