### ISSUE TITLE
So what is the "right" value for initBlur ?

### ISSUE THREAD

**Issue by alvaro562003** [Celebrandil/CudaSift#14]
Hello,
I am used to the matlab vlfeat to manage sift features. The command line is :

edge_thresh = 2.5;
[xy,descritor id] = vl_sift(single(rgb2gray(image_i)), 'edgethresh', edge_thresh) ;

With Cuda Sift it is :

upscale = false.
`ExtractSift(siftData1, img1, 7, initBlur, thresh, 0.0f, upscale);`

A priori, i know nothing about the image quality. So what is the "right" value for initBlur ?

Thank you

**Comment by Celebrandil** [comment]
For video camera images I would use something like 1.0 for initBlur, since those are typically noisier than what we can observe as humans. For high quality still images I would use 0.0 or possibly 0.5, if 0.0 results in more feature than I actually need.
