### ISSUE TITLE
Systematic Point Density

### ISSUE THREAD

**Issue by jlaura** [Celebrandil/CudaSift#15]
First, many thanks for keeping this project live. 

Below, I have an example image that I am attempting to extract key points for.  I am getting very strange systematic point distribution where the top of the higher has a significantly higher number of points.  In the example image, keypoints are still identified across the rest of the image.  In some cases, no points are found outside of the top of the image.

I am not sure if the total number of points (SiftData.maxPts) is being exceeded [here](https://github.com/Celebrandil/CudaSift/blob/Maxwell/cudaSiftH.cu#L168) and therefore breaking early?

Any insight appreciated.

![ctx_example](https://cloud.githubusercontent.com/assets/2105468/23884552/8a22ce96-082a-11e7-8b86-9a9f3f5623a2.png)

**Comment by Celebrandil** [comment]
It looks very much like as if you are reaching the maximum number of points. Large scale features are found first, but while extracting the finer scales you seem to reach the maximum. You should think of how many features you actually need and then either increase the maximum number of points (maxPts) or reduce the number of extracted features by either increasing the threshold (thresh) or the amount of initial blur (initBlur).
