### ISSUE TITLE
Matching.cu

### ISSUE THREAD

**Issue by rayhou0710** [Celebrandil/CudaSift#18]
Hi,
1) In the **matching.cu**, to my understanding the following kernel code in function **FindMaxCorr** is used to do the 'reduce job' of finding the best 2 matches. However, I am sort of confused about the outcome. Since in one block all threads with tx < 8 are concurrent threads how can we guarantee that the best match result is eventually swapped into the first entry? I would appreciate a lot if you can explain this part a little bit. 
  __syncthreads();
  for (int len=8;len>0;len/=2) {
    if (tx<8) {
      float val = maxScore[idx+len];
      int i = maxIndex[idx+len];
      if (val>maxScore[idx]) {
	maxScor2[idx] = maxScore[idx];
	maxScore[idx] = val;
	maxIndex[idx] = i;
      } else if (val>maxScor2[idx])
	maxScor2[idx] = val;
      float va2 = maxScor2[idx+len];
      if (va2>maxScor2[idx])
	maxScor2[idx] = va2;
    }
    __syncthreads();

2) I tried two images of my own and found all matches have a very high ambiguity. 
Should the following be correct?
sift1[p1].ambiguity = (1 - maxScore[ty * 16]) / (1 - maxScore2[ty * 16] + 1e-6);

Thanks!

**Comment by Celebrandil** [comment]
1. After two Gin&Tonic it's a little hard to digest what I once coded. I'm not even sure that code is particularly good. I originally wrote it to double-check whether the features I got were of good enough quality. At least, the code needs to be updated. What the code does is updating the best match and if it's not the best match, then try the second best match. In the loop before we have already come down to a reduction where there are only 16 candidates left and in this loop the last 16 are tried. It's a gradual reduction with a factor of 2. I believe that (tx<8) can be changed to (tx<len), but that won't change anything in terms of speed. 

2. Yes, if you want to do it the way Lowe does, it ought to be something like that. Assume B1 is the closest match and B2 is the second closest to A, and then assume they all have a length equal to 1. Then Lowe's measure ought to be (A-B2)^2/(A-B1)^2 = (1-2*A*B2+1)(1-2*A*B1+1) = (1-A*B2)/(1-A*B1) = (1-maxScor2[ty*16])/(1-maxScor[ty*16]) or possibly the square root or inverse thereof. You better draw the matches and see how things look like. In many scenes, such as office environments, there are far too many features that look the same. The measure works fine for object recognition, but in some cases it's not ideal.

**Comment by rayhou0710** [comment]
Hi Celebrandil,

Thanks for the reply. I understood the logic of the code - a 'gradual' reduction with a factor of 2. 
I previously didn't notice that the __syncthreads() is in the for loop.
