### ISSUE TITLE
i'm sorry ,How to run this code.

### ISSUE THREAD

**Issue by mindfusionofhue** [Celebrandil/CudaSift#19]
i'm sorry ,How to run this code.

**Comment by Celebrandil** [comment]
Just run the executable ./cudasift from the build directory after running cmake and make. The code is in mainSift.cpp, a file you can modify for your own purposes. Good luck!

**Comment by mindfusionofhue** [comment]
I thank very much

2017-05-22 3:20 GMT+08:00 Mårten Björkman <notifications@github.com>:

**Comment by mindfusionofhue** [comment]
i'm so sorry ,but t not find your makefile  file .

2017-05-22 9:55 GMT+08:00 qiangwei jiang <mindfusion2017@gmail.com>:

**Comment by Celebrandil** [comment]
The code uses CMake, so you need to have that installed. Create a build directory (mkdir build), jump to that directory (cd build), run CMake (cmake ..) and run make, using the Makefile that CMake generated.
