### ISSUE TITLE
Out of Memory error

### ISSUE THREAD

**Issue by rremani** [Celebrandil/CudaSift#22]
Hi @Celebrandil ,
I have got out of memory error when I try to MatchSiftData() of nearly 20000 features from each image. Does it related to memory allocation error.
Thanks

**Comment by Celebrandil** [comment]
The problem is likely due to the fact that MatchSiftData (currently) creates a matrix of numPts1*numPts2 floats, which is 1.6 Gb in your case. I've been thinking of using another approach without such a requirement, but haven't yet done that.

**Comment by rremani** [comment]
Ohk, thanks a lot.
