### ISSUE TITLE
cc: error: unrecognized command line option ‘-msse2’

### ISSUE THREAD

**Issue by zjutsonggz** [Celebrandil/CudaSift#30]
nvidia@tegra-ubuntu:/usr/local/CudaSift-Maxwell/build$ make
[ 14%] Building NVCC (Device) object CMakeFiles/cudasift.dir/cudasift_generated_matching.cu.o
cc: error: unrecognized command line option ‘-msse2’
CMake Error at cudasift_generated_matching.cu.o.cmake:207 (message):
  Error generating
  /usr/local/CudaSift-Maxwell/build/CMakeFiles/cudasift.dir//./cudasift_generated_matching.cu.o

CMakeFiles/cudasift.dir/build.make:77: recipe for target 'CMakeFiles/cudasift.dir/cudasift_generated_matching.cu.o' failed
make[2]: *** [CMakeFiles/cudasift.dir/cudasift_generated_matching.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cudasift.dir/all' failed
make[1]: *** [CMakeFiles/cudasift.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by J0hannB** [comment]
How did you fix this error?

I am also trying to build for Jetson and running into the same issue.

**Comment by kumar-akshay324** [comment]
Any solution for this guys?

**Comment by softwarePupil** [comment]
> Any solution for this guys?

Did you solve this problem, I was troubled by the same problem
