### ISSUE TITLE
May I ask what is Lowpass (host) function doing? Didn't find that in original paper

### ISSUE THREAD

**Issue by ghost** [Celebrandil/CudaSift#31]
Hi, first of all thank you for providing the cuda version of SIFT as its very helpful for me on my self-learning computer vision process. I tried to follow the code all the way down but got stuck somewhere in the middle. I couldn't figure out what is Lowpass function (the host one) doing before extracting sift descriptors, and what are those global variables beginning with "LOWPASS_". I tried to find an explanation in paper but failed ( or maybe I didn't read it too carefully). So may I ask for some instruction on that? Thank you. Since this is not a bug I will close it as soon as answered.

**Comment by theNded** [comment]
In this case, low pass filter is a Gaussian filter.
If you want to know the role of the Gaussian filter, please refer to [Scale-space Extrema Detection](http://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_feature2d/py_sift_intro/py_sift_intro.html#scale-space-extrema-detection).

**Comment by ghost** [comment]
Thank you for the explanation!
