### ISSUE TITLE
the sequence of descriptor

### ISSUE THREAD

**Issue by shaunzhuyw** [Celebrandil/CudaSift#36]
hello,  what  the difference between 128 dimension descriptor of cudasift and  that of lowe's sift.  as for the same postion of the same image,  are the descriptor same? if not, what the difference?  thank you very much.

**Comment by Celebrandil** [comment]
That is very hard to tell, without knowing all the particular details of Lowe's implementation. Even if you study the details in Lowe's papers, there are a number of minor things left to the implementor to decide, such as exactly what scales to use at different stages of computations and how filters are implemented. Even if each bin in the descriptor should have the same meaning, they will never be perfectly the same.
