### ISSUE TITLE
Some proposal for less gpu memory cost

### ISSUE THREAD

**Issue by colinlin1982** [Celebrandil/CudaSift#37]
First of all, thank you very much for this excellent work.
As I work on my cuda-affine-sift project base on this, it went out of memory when sift points count grows up to more than 25600.
I resolve this problem by these steps:
in file matching.cu, function MatchSiftPoints2:
1. I removed the memory copy codes (from sift1, sift2 to siftPoints1, siftPoints2), because I think pt1 and pt2 can directly point to sift1[n1].data and sift2[n2].data.
2. We only need to know max sum score, max sum index and second max sum score for each point in sift1, if we define grid and block like those for funciton FindMaxCorr:
  dim3 blocksMax(iDivUp(numPts1, 16));
  dim3 threadsMax(16, 16);
then these array is enough:
  __shared__ float maxScore[16 * 16];
  __shared__ float maxScor2[16 * 16];
  __shared__ int maxIndex[16 * 16];

Yes, as you guess, I combine function MatchSiftPoints2 and FindMaxCorr together, and compare the sum values as soon as they are calculated. My codes:

`

__global__ void MatchSiftPoints(float *corrData, SiftPoint *sift1, SiftPoint *sift2, int numPts1, int numPts2)
{
	int block_dim = blockDim.x; // blockDim.x == 16
	const int tx = threadIdx.x;
	const int ty = threadIdx.y;
	const int p1 = blockIdx.x * block_dim + ty;
	const int idx = ty * 16 + tx;

	__shared__ int maxIndex[16 * 16];
	maxIndex[idx] = 0;
	__syncthreads();

	float *corrs = NULL;

	if (p1 < numPts1) {
		corrs = &corrData[p1 * block_dim * 2];
		corrs[tx] = 0.0f;
		corrs[tx + 16] = 0.0f;
		const float *pt1 = sift1[p1].data;
		for (int p2 = tx; p2 < numPts2; p2 += 16) {
			float *pt2 = sift2[p2].data;
			float sum = 0.0f;
			for (int i = 0; i < 128; i++) {
				//int itx = (i + tx) & 127; // avoid bank conflicts
				sum += pt1[i] * pt2[i];
			}
			if (sum > corrs[tx]) {
				corrs[tx + 16] = corrs[tx];
				corrs[tx] = sum;
				maxIndex[idx] = p2;
			}
			else if (sum > corrs[tx + 16])
				corrs[tx + 16] = sum;
		}
	}
	__syncthreads();

	//if (p1==1)
	//  printf("tx = %d, score = %.2f, scor2 = %.2f, index = %d\n", 
	//	   tx, maxScore[idx], maxScor2[idx], maxIndex[idx]);

	if (p1 < numPts1) {
		for (int len = 8; len > 0; len /= 2) {
			if (tx < len) {
				float val = corrs[tx + len];
				int i = maxIndex[idx + len];
				if (val > corrs[tx]) {
					corrs[tx + 16] = corrs[tx];
					corrs[tx] = val;
					maxIndex[idx] = i;
				}
				else if (val > corrs[tx + 16])
					corrs[tx + 16] = val;
				float va2 = corrs[tx + 16 + len];
				if (va2 > corrs[tx + 16])
					corrs[tx + 16] = va2;
			}
			__syncthreads();
			//if (p1 == 1 && tx<len)
			//	printf("tx = %d, score = %.2f, scor2 = %.2f, index = %d\n",
			//		tx, corrs[tx], corrs[tx + 16], maxIndex[idx]);
		}
		if (tx == 6)
			sift1[p1].score = corrs[0];
		else if (tx == 7)
			sift1[p1].ambiguity = corrs[16] / (corrs[0] + 1e-6);
		else if (tx == 8)
			sift1[p1].match = maxIndex[ty << 4];
		else if (tx == 9)
			sift1[p1].match_xpos = sift2[maxIndex[ty << 4]].xpos;
		else if (tx == 10)
			sift1[p1].match_ypos = sift2[maxIndex[ty << 4]].ypos;
	}
	__syncthreads();
	//if (p1 == 1 && tx == 0)
	//	printf("index = %d/%d, score = %.2f, ambiguity = %.2f, match = %d\n",
	//		p1, numPts1, sift1[p1].score, sift1[p1].ambiguity, sift1[p1].match);
}

`

codes affected in function MatchSiftData:
`

	int block_dim = 16;
	float *d_corrData;
	int corrSize = numPts1 * block_dim * 2;
	safeCall(cudaMalloc((void **)&d_corrData, sizeof(float) * corrSize));
	//double allocTime = timer.read();

	dim3 blocks(iDivUp(numPts1, block_dim));
	dim3 threads(block_dim, block_dim); // each block: 1 points x 16 points
	//std::cout << "numPts1=" << numPts1 << ",numPts2=" << numPts2 << ",corrSize=" << corrSize << std::endl;
	MatchSiftPoints << <blocks, threads >> > (d_corrData, sift1, sift2, numPts1, numPts2);
	safeCall(cudaThreadSynchronize());
	checkMsg("MatchSiftPoints() execution failed\n");

	//double matchTime = timer.read();
	//printf("MatchSiftPoints time =          %.2f ms\n", (matchTime - allocTime));

	safeCall(cudaFree(d_corrData));

`
It works for me, as I can match more than 32000 points for each image on GTX1060 6G.

**Comment by Celebrandil** [comment]
Thank you very much for your suggestions. I will definitely take a look at them. That code has not been changed much in recent years, but the O(N^2) memory requirement has always annoyed me. It does make perfect sense to rely on global reads, instead of using shared memory buffers. Caching has improved considerably in newer GPU versions and the benefit of shared memories is no longer as obvious.

**Comment by Celebrandil** [comment]
When testing what you suggested on a Titan Xp the current code is about 5 times faster (when matching about 10K vs 13K points), so it seems you still benefit quite a bit from the shared memory, at least on that GPU. I dropped the extra global memory completely in another version and got down to a factor of about 3 slower, which is still a bit much. Having two kinds of operation modes might be an idea, since getting rid of extra memory requirement is sometimes important.

**Comment by Celebrandil** [comment]
I think I have a version that is similar in speed to the existing version, but without the extra global memory requirement. Thank you for kicking my butt!

```
#define FMC2W 16
#define FMC2H 8

__global__ void FindMaxCorr4(SiftPoint *sift1, SiftPoint *sift2, int numPts1, int numPts2)
{
  __shared__ float siftPoint[128*FMC2H];
  __shared__ float maxScore[FMC2H]; 
  __shared__ float maxScor2[FMC2H]; 
  __shared__ int maxIndex[FMC2H]; 
  const int tx = threadIdx.x;
  const int ty = threadIdx.y;
  if (tx==0) {
    maxScore[ty] = -1.0f;
    maxScor2[ty] = -1.0f;
    maxIndex[ty] = 0;
  }
  const int p1 = blockIdx.x*FMC2H + ty;
  const float *pt1 = sift1[p1].data;
  for (int j=tx;j<128;j+=FMC2W)
    siftPoint[128*ty + j] = pt1[j];
  __syncthreads();
  for (int p2=0;p2<numPts2;p2++) {
    const float *pt2 = sift2[p2].data;
    float sum = 0.0f;
    for (int j=tx;j<128;j+=FMC2W)
      sum += siftPoint[128*ty + j] * pt2[j]; 
    for (int j=FMC2W/2;j>0;j/=2)
      sum += __shfl_down_sync(0xffffffff, sum, j);
    if (tx==0) {
      if (sum>maxScore[ty]) {
	maxScor2[ty] = maxScore[ty];
	maxScore[ty] = sum;
	maxIndex[ty] = p2;
      } else if (sum>maxScor2[ty])
	maxScor2[ty] = sum;
    }
  }
  if (tx==0) {
    sift1[p1].score = maxScore[ty];
    sift1[p1].ambiguity = maxScor2[ty] / (maxScore[ty] + 1e-6);
    sift1[p1].match = maxIndex[ty];
    sift1[p1].match_xpos = sift2[maxIndex[ty]].xpos;
    sift1[p1].match_ypos = sift2[maxIndex[ty]].ypos;
  }
}

  dim3 blocksMax(iDivUp(numPts1, FMC2H));
  dim3 threadsMax(FMC2W, FMC2H);
  FindMaxCorr4<<<blocksMax, threadsMax>>>(sift1, sift2, numPts1, numPts2);
  safeCall(cudaThreadSynchronize());
  checkMsg("MatchSiftPoints() execution failed\n");
```

**Comment by colinlin1982** [comment]
You are right. I test your code and it is much faster than mine.
Thank you.
