### ISSUE TITLE
checkMsg() CUDA error: LowPass() execution failed

### ISSUE THREAD

**Issue by FrancoisDuBois92** [Celebrandil/CudaSift#44]
When I try and run cudasift I get the following output:

Image size = (0,0)
Initializing data...
Device Number: 0
  Device name: GeForce GTX 860M
  Memory Clock Rate (MHz): 2505
  Memory Bus Width (bits): 128
  Peak Memory Bandwidth (GB/s): 80.2

Failed to allocate device data
Failed to allocate device data
Failed to allocate device data
checkMsg() CUDA error: LowPass() execution failed in file </home/francois/Desktop/P3_CV3/CudaSift/cudaSiftH.cu>, line 416 : invalid configuration argument.

Does anyone know a solution to the problem?

**Comment by Celebrandil** [comment]
Make sure that you run the code from the top directory, so that image files can be found in the data folder. The fact that the image size is (0,0) is an indication that no image files could be found.
