### ISSUE TITLE
Licensing and attribution

### ISSUE THREAD

**Issue by danielsuo** [Celebrandil/CudaSift#5]
Sorry to bother again so soon, but someone reached out to us asking about commercial licensing our fork of CudaSift (link [here](https://github.com/danielsuo/cusift)). They are aware of David Lowe's original patent, but I wanted to a) properly attribute the work you did and b) protect both of us from liability. Do you have thoughts on how you would license CudaSift?

I was thinking of using of using the MIT License or even the Unlicense, but wanted to check with you first. Let me know!

**Comment by michaelgruner** [comment]
Hi, I'm interested in using your CudaSift. Did you come to any resolution regarding licensing?

**Comment by Celebrandil** [comment]
After quite a bit of consideration I finally adapted the MIT license. I didn't want to get into any trouble due to the patent that exists on the SIFT algorithm itself.
