### ISSUE TITLE
Invalid configuration argument

### ISSUE THREAD

**Issue by griegler** [Celebrandil/CudaSift#50]
Hi,

I wanted to try out your code for a project of mine, but I get the following error:
```
checkMsg() CUDA error: LowPass() execution failed
 in file <cudaSiftH.cu>, line 416 : invalid configuration argument.
```

I have a Titan Xp, and use Cuda 9.2 (Ubuntu 16.04).
Any ideas?

**Comment by Celebrandil** [comment]
That's odd. You could get that error for older cards when a kernel uses more threads that what the card supports, but that is not the case here. LowPass is the first GPU kernel that is run by ExtractSift. Do you get the same error when the code is run standalone or only when integrating with something else?

**Comment by griegler** [comment]
I just run `./cudasift`, compiled without any modifications.

**Comment by Celebrandil** [comment]
Probably, no images were found and it gets "images" of size (0,0) to extract features from. Try to run it from the main directory of the repository, so that the data path is correct.

**Comment by griegler** [comment]
You were right. Thanks!
