### ISSUE TITLE
Detected keypoints are less than which is detected by VLFeat

### ISSUE THREAD

**Issue by PLester** [Celebrandil/CudaSift#57]
Hello!
  Thanks for your great work first!
  I don't know why the detected keypoints are less than the keypoints detected by the VLFeat?
  Can I change some parameters to increase the number of the detected keypoints?
  Thank you very much!

**Comment by Celebrandil** [comment]
You could change the threshold according to what is written at the end of the front page. The ideal threshold varies quite a lot depending on the contrasts of the images. The example images are quite high contrast, so the threshold used for those are quite large.

**Comment by PLester** [comment]
> You could change the threshold according to what is written at the end of the front page. The ideal threshold varies quite a lot depending on the contrasts of the images. The example images are quite high contrast, so the threshold used for those are quite large.

Thank U！
