### ISSUE TITLE
ERROR : safeCall() Runtime API error in file </home/kk/Documents/CudaSift-Maxwell/cudaSiftH.cu>, line 42 : invalid device symbol.

### ISSUE THREAD

**Issue by rajatnt** [Celebrandil/CudaSift#6]
Following is the  output when the object file is executed.
`[kk@localhost CudaSift-Maxwell]$ ./cudasift 
Image size = (1280,960)
Initializing data...
Device Number: 0
  Device name: GeForce 210
  Memory Clock Rate (MHz): 600
  Memory Bus Width (bits): 64
  Peak Memory Bandwidth (GB/s): 9.6

Download time =               0.92 ms
Download time =               0.89 ms
safeCall() Runtime API error in file </home/pict/Documents/CudaSift-Maxwell/cudaSiftH.cu>, line 42 : invalid device symbol.
[kk@localhost CudaSift-Maxwell]$ C
`
What is the problem?

**Comment by LucaLovagnini** [comment]
Same problem here.

**EDIT:**
Solved changing the CMakeLists.txt from sim_35 to sim_20
