### ISSUE TITLE
Why is gcc-6? Can I use gcc-5?  

### ISSUE THREAD

**Issue by Liber-coder** [Celebrandil/CudaSift#62]
I noted the `CUDA_NVCC_FLAGS` written in `CMakeLists.txt` used a `/usr/bin/gcc-6`. But, I have changed the `gcc-6` into a `gcc-5`, and compiled it successfully. Can I use `gcc-5`?  

My machine:
ubuntu 16.04
cuda 8.0 (gcc versions later than 5 are not supported!)
gcc-5.4.0

**Comment by Celebrandil** [comment]
You could change the version of GCC to a version that fits your CUDA version. I try to avoid exotic C++ features that might not exist in some platforms.
