### ISSUE TITLE
Error Linking Cudasift.lib to a project

### ISSUE THREAD

**Issue by HaiderAbasi** [Celebrandil/CudaSift#63]
I am unable to link cudasift.lib to my project so that i can access functions declared in the header files as used in the example (InitSiftData)
(compiled using cmake 3.14.2 and built using VS 2019
Cuda v10.1,
v9.2 installed)
1) Either cudasift.lib donot have the desired function definitions or i am unable to properly link to it.
2) included cudaImage.h and cudasift.h
3) cudasift.exe works fine (modified the mainSift.cpp to take images as the input arguments and perform detection and matches on the set)
4) What i require is to use the functionality of cudasift in my own project where i could call the functions declared in header and perform deteciton and matching for my own case just by importing the required library that holds all the defintions of cudasift.

![addition_inclde_dirs](https://user-images.githubusercontent.com/49869365/59246471-e4b91180-8c35-11e9-990b-140dd0d1c39e.PNG)
![addition_library_dirs](https://user-images.githubusercontent.com/49869365/59246472-e551a800-8c35-11e9-806a-9781d6c73a78.PNG)
![cudasift_lib](https://user-images.githubusercontent.com/49869365/59246474-e5ea3e80-8c35-11e9-8af6-25c29b0b595d.PNG)
![error](https://user-images.githubusercontent.com/49869365/59246476-e682d500-8c35-11e9-90ee-6a9b03078aed.PNG)
![install_dir](https://user-images.githubusercontent.com/49869365/59246477-e71b6b80-8c35-11e9-972b-060fc8312997.PNG)
![release_dir](https://user-images.githubusercontent.com/49869365/59246478-e7b40200-8c35-11e9-9496-cb1d30f1e2a6.PNG)

**Comment by Celebrandil** [comment]
I cannot tell what the error is, but a more frequent user of VS 2019 might. Since cudasift.lib is only 2 KB in size, it might not contain much.

**Comment by HaiderAbasi** [comment]
i managed to get what i wanted by making changes in the cmakelists.txt
instead of cmake_add_executable
i wrote cmake_add_library(STATIC,$src_files)
and i was able to acces all the functions :)
