### ISSUE TITLE
LaplaceMulti() execution failed

### ISSUE THREAD

**Issue by LucaLovagnini** [Celebrandil/CudaSift#7]
Hello,

I'm trying to run the `mainSift.cpp` program on a `Tesla M2090`. First of all I had to change all of `sim_35` occurences into `sim_20` in `CMakeLists.txt`. After that, this message is returned during the execution of `LaplaceMulti()`:

```
checkMsg() CUDA error: LaplaceMulti() execution failed
 in file </ghome/rzhengac/Downloads/CudaSift-Maxwell/cudaSiftH.cu>, line 324 : unknown error.
```

Why this happens?

**Comment by Celebrandil** [comment]
Quite a lot has changed since compute capability 2.0, but I cannot see why if should fail in LaplaceMulti(). The latest version was adapted for Maxwell though and that is a later generation.
